### ISSUE TITLE
upgrade framework 4

### ISSUE THREAD

**Issue by bbday** [synhershko/NAppUpdate#81] opened 2016-05-01 20:35 UTC
It is possible upgrade version that not require framework 2 / 3.5
cause some user don't have access to windows feature to enable them.

Last framework it is 4.6 it thing it is a good thing have framework 4 for prerequisite and not old framework.

**Comment by synhershko** [comment] 2016-05-02 12:40
Requiring the latest .NET framework will make that version of the framework a prerequisite, so using the latest is probably not a good idea. But I agree .NET 2 is too old at this point.

Closing as a duplicate of #27

**Closed by synhershko** 2016-05-02 12:40 UTC

**Comment by bbday** [comment] 2016-05-02 17:36
Consider also with windows 10, framework 2 / 3.5 it is not installed, cause it have only framework 4 installed.

**Comment by robinwassen** [comment] 2016-05-18 09:07
This issue will be solved by: https://github.com/synhershko/NAppUpdate/pull/85

Because that PR will include builds for both .Net 3.5 and .Net 4.0 in the nuget releases.
