### ISSUE TITLE
ConnectNamedPipe fails

### ISSUE THREAD

**Issue by svenbw** [synhershko/NAppUpdate#10] opened 2011-06-08 10:25 UTC
Sometimes this function fails although there is a pipe created.
It seems that the CreateNamedPipe function can report that the connection is complete when it's not ready yet.

Changing the code by checking on the 535 (ERROR_PIPE_CONNECTED) seems to overcome this issue.

    //failed to connect client pipe
    if ((success != 1) && (Marshal.GetLastWin32Error() != 535))
    {
        break;
    }

**Comment by robinwassen** [comment] 2015-07-11 09:37
@synhershko You have fixed this, so I think you can close it: https://github.com/synhershko/NAppUpdate/blob/bc22bb4909ce5c9fb7ef0c13fdacccf4999b2d24/src/NAppUpdate.Framework/Utils/NauIpc.cs#L134

**Comment by robinwassen** [comment] 2015-07-11 09:38
Nevermind, might need to be fixed here too: https://github.com/synhershko/NAppUpdate/blob/bc22bb4909ce5c9fb7ef0c13fdacccf4999b2d24/src/NAppUpdate.Framework/Utils/NauIpc.cs#L93

**Comment by robinwassen** [comment] 2015-10-26 22:32
Closing as duplicate of #54

**Closed by robinwassen** 2015-10-26 22:32 UTC
Labels: Bug
