### ISSUE TITLE
Error at Auto Updating Application using  NAppUpdate (Could not launch cold update process)

### ISSUE THREAD

**Issue by anupSharma** [synhershko/NAppUpdate#54] opened 2015-04-02 13:17 UTC
when use auto update app every time get bellow error.
Error while trying to install software updates
Could not launch cold update proc
![error](https://cloud.githubusercontent.com/assets/4352592/6964619/a0eaf54c-d968-11e4-951f-5f55eb7c3be5.PNG)
ess.

**Comment by synhershko** [comment] 2015-04-02 17:36
Can you try and provide more details on this please? there's not much for me to go on here

**Comment by anupSharma** [comment] 2015-04-03 10:33
We have used NAppUpdate.Framework.dll in app and after completion of "BeginPrepareUpdates" methods we are making call to "updManager.ApplyUpdates(true,true,true)" or even we have tried with t wo different overloaded versions of this method. API does download the updates in temp folder and also create backup folder and when it runs the  "updater.exe", it does prompt me for UAC but after that it throws below error:


------- 
"Error while trying to install software updates
Could not launch cold update proc"
![error](https://cloud.githubusercontent.com/assets/4352592/6981054/6bed11ac-da19-11e4-9766-3372b9bfbaf0.PNG)

And noticed that when we move application installation folder from Program files to other location (like Desktop) then except *.exe other files are updated. I also do not see where my apps exe is closed before restart.
Tried your sample app too and getting same results. 

I hope it will help you in further debugging..

**Comment by robinwassen** [comment] 2015-07-10 13:26
Our users have also experienced this problem on 23 different machines since we started to log this error.

I do not have a clean reproduction case, but I think it might be related to the UAC settings since it is thrown when `NauIpc.LaunchProcessAndSendDto()` return null. And it does that [if the user does not elevate UAC](https://github.com/synhershko/NAppUpdate/blob/bc22bb4909ce5c9fb7ef0c13fdacccf4999b2d24/src/NAppUpdate.Framework/Utils/NauIpc.cs#L113).

A good step in the right direction would be to not supress the exceptions.

**Comment by synhershko** [comment] 2015-07-10 14:16
PRs welcome

**Comment by robinwassen** [comment] 2015-07-10 22:30
@synhershko Delivered: https://github.com/synhershko/NAppUpdate/pull/55 :)

**Comment by robinwassen** [comment] 2015-09-22 14:47
I have investigated this issue further - it seems like the `ManualResetEvent` simply timeout before it manage to connect to the pipe. But why it fails to connect to the pipe is still unknown to me.

Will keep updating my progress at: https://github.com/robinwassen/NAppUpdate2/issues/1

**Comment by robinwassen** [comment] 2015-10-26 22:12
I got to see this problem with my own eyes for the first time, could not debug it but it took approximately 10 seconds before the exception was thrown.

Which leads me into that it is due to a timeout of the ManualResetEvent.

If a timeout occurs the whole `Marshal.GetLastWin32Error()` part is bypassed and therefore we don't get the error.

Need to redo the error handling so it is done even though it is a `ManualResetEvent` timeout.

**Comment by robinwassen** [comment] 2016-02-04 16:29
@synhershko I rewrote the Win32 pipe handling with .NET 3.5 way of managing pipes in the branch: https://github.com/synhershko/NAppUpdate/tree/54-timeout-error-handling

In order to do this I bumped up the .NET Framework version from 2.0 to 3.5, but as far as I remember there should be no compatibility issues due to this.

Also uploaded my test app project here: https://storage.googleapis.com/digiexam/temp/ConsoleNamedPipe.zip

Do you have any obvious objections to what I did? I need to do some more thorough testing before I proceed to do a PR.

**Comment by synhershko** [comment] 2016-03-01 16:44
@robinwassen I'm thinking this is fixed now?

**Comment by robinwassen** [comment] 2016-04-06 09:31
@synhershko This has not been fixed, we hoped that the recent major rewrite of the related code would solve the problem.

    Could not launch cold update process
    System.TimeoutException: The NamedPipeServerStream timed out waiting for a named pipe connection, but the process has exited with exit code: -2146232576 (System.Runtime.InteropServices.COMException)
     at NAppUpdate.Framework.Utils.NauIpc.LaunchProcessAndSendDto(NauDto dto, ProcessStartInfo processStartInfo, String syncProcessName)
     at NAppUpdate.Framework.UpdateManager.ApplyUpdates(Boolean relaunchApplication, Boolean updaterDoLogging, Boolean updaterShowConsole)

Second exception:

    Could not launch cold update process
    System.IO.IOException: All pipe instances are busy
    
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.Pipes.NamedPipeServerStream.Create(String fullPipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeAccessRights rights, SECURITY_ATTRIBUTES secAttrs)
     at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeSecurity pipeSecurity, HandleInheritability inheritability, PipeAccessRights additionalAccessRights)
     at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
     at NAppUpdate.Framework.Utils.NauIpc.LaunchProcessAndSendDto(NauDto dto, ProcessStartInfo processStartInfo, String syncProcessName)
     at NAppUpdate.Framework.UpdateManager.ApplyUpdates(Boolean relaunchApplication, Boolean updaterDoLogging, Boolean updaterShowConsole)

We just need to gather some more information about why the updater exits with error code -2146232576 now.

**Comment by robinwassen** [comment] 2016-05-18 09:10
I think we found the root of the problem. 

Our application was built using .NET 4.x and it embedded the updater which was built using .NET 3.5. When computers don't have .NET 3.5 installed the updater wont start and the application will crash.

Closing this ticket as: https://github.com/synhershko/NAppUpdate/pull/85 will solve this, just make sure that you include NAppUpdate with the same .NET version as your application.

**Closed by robinwassen** 2016-05-18 09:10 UTC
Labels: Bug
